import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getUserById } from "@/lib/admin/users";

export const dynamic="force-dynamic";
export const metadata:Metadata={title:"User | Bittumama",robots:{index:false,follow:false,nocache:true,noarchive:true}};
function formatDate(value:Date){return new Intl.DateTimeFormat("en-IN",{dateStyle:"full",timeStyle:"short"}).format(value);}
export default async function AdminUserDetailPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const user=await getUserById(id);if(!user)notFound();return <section aria-labelledby="user-title" className="max-w-4xl"><div className="border-b border-border pb-6"><Link href="/admin/users" className="text-sm underline underline-offset-4">← All users</Link><p className="type-label mt-5 text-muted-foreground">User</p><h1 id="user-title" className="type-h2 mt-2">{user.name||"Unnamed user"}</h1><p className="mt-2 break-words text-sm text-muted-foreground">{user.email||"No email address"}</p></div><div className="mt-8 space-y-8"><section aria-labelledby="account-title"><h2 id="account-title" className="type-h5">Account</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Authentication providers</dt><dd className="mt-1 text-sm">{user.accounts.map(a=>a.provider).join(", ")||"Email password"}</dd></div><div><dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Created</dt><dd className="mt-1 text-sm">{formatDate(user.createdAt)}</dd></div><div><dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Updated</dt><dd className="mt-1 text-sm">{formatDate(user.updatedAt)}</dd></div></dl></section><section aria-labelledby="relationships-title"><h2 id="relationships-title" className="type-h5">Relationships</h2><p className="mt-3 text-sm">{user._count.contactInquiries} associated contact {user._count.contactInquiries===1?"inquiry":"inquiries"}.</p><p className="mt-2 text-xs text-muted-foreground">Administrator credentials are stored separately and are never exposed through normal user management.</p></section></div></section>;}
