name: Build

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24.21.0"

      - name: Install dependencies
        run: npm install

      - name: Prisma generate
        run: npm run prisma:generate

      - name: Prisma schema validation
        run: npm run prisma:validate

      - name: Lint
        run: npm run lint

      - name: Production build
        run: npm run build
